services:
  web:
    image: monum/server:v2
    container_name: fastapi_app
    ports:
      - "80:8000"
    depends_on:
      - redis
  search:
    image: monum/search:v1
    container_name: search_app
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - web
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
