services:
  web:
    image: monum/fastapi-app:v4
    container_name: fastapi_app
    ports:
      - "80:8000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
